log:
  level: info
  file: "/var/log/mosdns/mosdns.log"

plugins:
  - tag: main_server
    type: server
    args:
      entry: main_sequence
      protocol: udp
      addr: ":53"

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - forward_local
        - _return

  - tag: forward_local
    type: forward
    args:
      upstreams:
        - addr: "udp://127.0.0.1:53"
